{{- range $service := .Values.services }}
{{- if $service.enableVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-{{ substr 0 10 $.Values.global.env.INSTANCE_ID | lower }}-pv
spec:
  capacity:
    storage: {{ $service.volume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/server_data/{{ $.Values.global.appName }}/{{ $service.name }}-{{ substr 0 10 $.Values.global.env.INSTANCE_ID | lower }}"
    type: DirectoryOrCreate
---
{{- end }}
{{- end }}
