{{- range $service := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-{{ $.Values.global.env.INSTANCE_ID }}-ingress
  namespace: {{ $.Values.global.appName }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: {{ $.Values.global.ingressURL }}
    http:
      paths:
        - path: {{ $service.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $.Values.global.appName }}-{{ $service.name }}-{{ $.Values.global.env.INSTANCE_ID }}-service
              port:
                number: 80
  tls:
  - hosts:
    - "*.{{ $.Values.global.ingress.domain }}"
    secretName: wildcard-tls-secret
---
{{- end }}
