global:
  imageRegistry: "docker.io/nocodebi"
  image:
    tag: "latest"
  ingress:
    className: "traefik"
    domain: nocodebi.io
  appName: app
  userHome: ""
  ingressURL: ""
  env:
    DATA_DIR: "/app/data/"
    CENTRAL_SERVER_URL: "https://central.nocodebi.io"
    PRODUCT_CONSOLE_SERVER_URL: "https://local-product.nocodebi.io"
    APP_SERVER_URL: ""
    STAGE_ID: ""
    APP_ID: ""
    VERSION_ID: ""
    USER_ID: ""
    PREMISES_SHA: ""
    CORE_JAR_URL: ""
    M2_ZIP_URL: ""
    APP_DATA_PATH: ""
  tls:
    crt: ""
    key: ""
  tls2:
    crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0RENDQXNpZ0F3SUJBZ0lVYnNNODN6b2lyclVic0lpeVBlN1hsYkhVVWQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2JERUxNQWtHQTFVRUJoTUNTVTR4RkRBU0JnTlZCQWdNQzAxaGFHRnlZWE5vZEhKaE1RMHdDd1lEVlFRSApEQVJRZFc1bE1SRXdEd1lEVlFRS0RBaE9iME52WkdWQ1NURU5NQXNHQTFVRUN3d0VWR1ZqYURFV01CUUdBMVVFCkF3d05LaTV1YjJOdlpHVmlhUzVwYnpBZUZ3MHlOVEE1TVRBd09UVTJNVEphRncwek5UQTVNRGd3T1RVMk1USmEKTUd3eEN6QUpCZ05WQkFZVEFrbE9NUlF3RWdZRFZRUUlEQXROWVdoaGNtRnphSFJ5WVRFTk1Bc0dBMVVFQnd3RQpVSFZ1WlRFUk1BOEdBMVVFQ2d3SVRtOURiMlJsUWtreERUQUxCZ05WQkFzTUJGUmxZMmd4RmpBVUJnTlZCQU1NCkRTb3VibTlqYjJSbFlta3VhVzh3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzYKY2JrSEEvUGdQVnVleEl2RDJMOHFLWkpLNVZuV0xMM0hmRldxY3JZN29Vd0ltYys5ZGVIMHVmK1Nqc2MvSzJ4cApxcUcrMlBocGw3Mk5YS3l5R28rTVFUZTkwZ2dCTVgweGx0VHRXaS9TejJ5QUNlTXdqN2QrUWQ0a1puOW55ZGtoCjhSSU1WZnlSL3lIYWxPbFZ6a1ZKYWErNzM1UjB6a09nQmtmdnpmSkRtNVRFMXh4enlOd1FKM1VwUmx0OVM1Z1oKcE1ydHErVVdCaGNtZVhiV2Uyb3hPSzdIOTlEOXU1QUU5NFE0UjBXbkh4RVNMOUNHUUdTKzN0SjN6VjU4YWl1cwpsck82aDJ0V1hTazdjMTV3Vm4yNHRQNlArNW5NL0c1R3RrcGgyVXh3TEYwdDkzb0gvcjI5aFJ4cVEzeVA2bDB6CjNIalAybWxTUUpMaG10NlRxaWpCQWdNQkFBR2plakI0TUIwR0ExVWREZ1FXQkJRRzZBMVVnOTkwUk9MVUgySkkKelpudzF6cjNPREFmQmdOVkhTTUVHREFXZ0JRRzZBMVVnOTkwUk9MVUgySkl6Wm53MXpyM09EQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQ1VHQTFVZEVRUWVNQnlDRFNvdWJtOWpiMlJsWW1rdWFXK0NDMjV2WTI5a1pXSnBMbWx2Ck1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnk1T2RpSCs1cnQzWThGaVMrZ1RhWTZuOTZhT09jckJZZnh1a2EKUE5zREZ3Q3d1amJoVExncHZSMTBXYzljUEhVSHVuY2QyKzl1MmoxZE51K1NpQU1kdmhZV29DamlOa2IwclphaQppN1VOMmNaNVRndXFMeHFXVE9DVHJBenpENEhDRmRTcWp6SWRnOGJXWWVFNHd1VytsK2xBMXo3Q2ZYWGZyV3g3CkhwN0ZPSkFyYXowcFpvRTdLd0ZEdk5tcVJrcVV1M3Q1T2hSQzZlbXpMY3ZEbm8wZ0ZuckNma1RsMGVicUo5b0oKWmdDdUdLb2xiS0sxcFAvQjhHOXZkRWhZUzJ4a1lOTnByVzZLNGJORi9ac2tzNE1Oc0ZhQWxISFpzb1BlY29EdgpCWlgwZDNlekZReXhvL2UzUHZMSkdveEZKR21yb1NpeUMzemZGd2JScnFUSGFVSWUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQzZjYmtIQS9QZ1BWdWUKeEl2RDJMOHFLWkpLNVZuV0xMM0hmRldxY3JZN29Vd0ltYys5ZGVIMHVmK1Nqc2MvSzJ4cHFxRysyUGhwbDcyTgpYS3l5R28rTVFUZTkwZ2dCTVgweGx0VHRXaS9TejJ5QUNlTXdqN2QrUWQ0a1puOW55ZGtoOFJJTVZmeVIveUhhCmxPbFZ6a1ZKYWErNzM1UjB6a09nQmtmdnpmSkRtNVRFMXh4enlOd1FKM1VwUmx0OVM1Z1pwTXJ0cStVV0JoY20KZVhiV2Uyb3hPSzdIOTlEOXU1QUU5NFE0UjBXbkh4RVNMOUNHUUdTKzN0SjN6VjU4YWl1c2xyTzZoMnRXWFNrNwpjMTV3Vm4yNHRQNlArNW5NL0c1R3RrcGgyVXh3TEYwdDkzb0gvcjI5aFJ4cVEzeVA2bDB6M0hqUDJtbFNRSkxoCm10NlRxaWpCQWdNQkFBRUNnZ0VBSEJCT0hOaml5KzFiR0hUV2pOalg2Q0xGeGNici8zNzdPZkc1MEtRMCswTjIKSWIxS2l4RnV2TnJhWUt4anlyQmdsZG5SNnR1QjJNaGhzY3VIVUcrMXQ3NHNBOE1xTi9QRHQ4UFBzbTBSZkd2WQpheFZuUUd5c05BYjZIRm5lbk9MQnhOMTMxLytCWmFzVTVNVThCMmNRVlgwMldkTWlQTXE4c2NrQVB2K3Rrd1lGCnBiWXJEOHRsMjZIeTVQbThxL05FNWtlbmNVVnVhWWNSVGZ4RkF3Zk5YWUZDQ1ZYeXNSN2lHV3dtbm9wL1hIRkwKYTlxT1VwazY2b1hPRHY3c01zNUhRK0lMdHZ4ajdyZlBDeVEvRmVoNndqOXZKOWd3T2dXQWVHbENHMWFhU0lKNgpjSzFYMkMwdzBqU2NJZ21aY0RWTWVvMXFJSVpFVHBOTTVtd251MkZEMlFLQmdRRGhoTzNORzM5OUM1bXRHZm1hCmp6ak9jWWR2N09hZTlielpMWm91eU9zY2NrZkdCS0d0eDdEVzBOQTRFdWVnSjBKb2JmVUNJUmR0eUQwR0pzTnIKUko4TVlwRi9SODE5dmhIcHN4ZFJHdXhqNE1rN0Y2TUVWVGFDV0kxK05OZW53N2lTSDNrWmNpWUMvYUo5a2VJVwpyaE1SSDR2ZlUyMnVFcDI1cWNMUDQ2TCtJd0tCZ1FEVHBNZWp5b01MTkFoQjY0RmY0VzJUM09jQTZUZ0ZaVzhCClpGc1lRSEVINXpmc2N6TVYzSnVXQmZRd2xjekQ0ODhaTkpJblJpYTZhc0RzcW1PczkyZWZtdUtHOXFqVUVKTnEKZ0NBaUxWYjd5bFcyUElVQ3JyRmozSnNvNUlQVEJ6b29LQ2dJWVlsbGp3cmpVb09IWFQ3dHNLWE9RVXd6bjM0bQpXakY3TVdtQnl3S0JnUURKRExMYjJobnNKcjFZUHdIeE1xSFlHZ28rVkJxOXVDSW1FNnVTN2ZmOG9qMHVZYzZwCm1JOGswMy90blp6MWdFcUp3dzFjV3BnQ2ZUTTZHckM1SHJJVVhvT0x6ejE1VGt1MTVyMXd4dW5ibVBpTlArTksKNTVUeTIzTTVBbThIMTByaXFrQlIyUnZlS3JRRDhseDNEN1ZiM0ozYitRcWMxMmZacjJoSDRZN2J0UUtCZ1FDMApXNE1KOEtVVjRnUjdjSjl5dnQrcmx4K0FwajVvVXRWeklUdUVBajZRbHBrUXRlYzk1Ujd0alN0WVVBQU1tMUU4ClVKR1FTSGJ1ZTlUbW1obVJKOUMxc2I4RGRxWE8ra1UyQi9QYVREc0pIWmRIVW5HakpJM2s1UFdRdHBRa1BNOXgKc3k3U1haUkI2TkZGZ1dhMjcxNldIZWhlU1VVUDVRWVMxdCs5OVJETld3S0JnUUNXWXFZc1ZEbFRpREtQZHh0RwpzM1dNRWhua0NEanRFZDk4OUcvbitGOVBiclIyaGwzUlJ1MFV2a3RWaEh0YjlwSWRSUU9aclFsRTRURHZrOFAyCkdSdXZYMXVKQTcrWVYycmZjeHcyelhjWXJBY3MxMVNiaEg2Sk9IOXpUUjhlbW1GQ21NOHpHbk9ENlI3R1dhYi8KTFl5V1hHTnd0MTZpejVKRzE4cmxkZFBwUUE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="

services:
- name: appserver-admin
  image: appserver-admin
  port: 10002
  path:
  - /
  subDomain: local-
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: false
  volume:
    size: 10Gi

- name: appserver-flow
  image: appserver-flow
  port: 10009
  path:
  - /flow
  subDomain: local-
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: true
  volume:
    size: 10Gi

- name: appserver-hosted-database
  image: appserver-hosted-db
  port: 10004
  path:
  - /hostedDB
  - /connector-server
  subDomain: local-
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: true
  volume:
    size: 10Gi

- name: appserver-query
  image: appserver-query
  port: 10005
  path:
  - /query
  subDomain: local-
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: true
  volume:
    size: 10Gi

- name: appserver-view
  image: appserver-view
  port: 10006
  path:
  - /preview
  - /page
  - /view
  - /config
  subDomain: local-
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: true
  volume:
    size: 10Gi

# - name: appserver-configuration
#   image: appserver-configuration
#   port: 10007
#   path: /config
#   subDomain: local-
#   replicaCount: 1
#   autoscaling:
#     enabled: false
#     minReplicas: 1
#     maxReplicas: 5
#     targetCPUUtilizationPercentage: 70
#     targetMemoryUtilizationPercentage: 80
#   enableVolume: true
#   volume:
#     size: 10Gi

# - name: appserver-connector
#   image: appserver-connector
#   port: 10003
#   path: /connector-server
#   subDomain: local-
#   replicaCount: 1
#   autoscaling:
#     enabled: false
#     minReplicas: 1
#     maxReplicas: 5
#     targetCPUUtilizationPercentage: 70
#     targetMemoryUtilizationPercentage: 80
#   enableVolume: true
#   volume:
#     size: 10G

# - name: appserver-security-provider
#   image: appserver-security
#   port: 10008
#   path: /security
#   subDomain: local-
#   replicaCount: 1
#   autoscaling:
#     enabled: false
#     minReplicas: 1
#     maxReplicas: 5
#     targetCPUUtilizationPercentage: 70
#     targetMemoryUtilizationPercentage: 80
#   enableVolume: true
#   volume:
#     size: 10Gi
