{{- range $service := .Values.services }}
{{- if $service.enableVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-pv
spec:
  capacity:
    storage: {{ $service.volume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/server_data/{{ $.Values.global.appName }}/{{ $service.name }}"
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ $.Values.global.appName }}
    name: {{ $.Values.global.appName }}-{{ $service.name }}-pvc
---
{{- end }}
{{- end }}
