{{- range $service := .Values.services }}
{{- if $service.enableVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.global.appName }}-{{ $service.name }}-{{ substr 0 8 $.Values.global.env.INSTANCE_ID | lower }}-pv
spec:
  capacity:
    storage: {{ $service.volume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ $.Values.global.userHome }}/data/{{ $.Values.global.appName }}/{{ $service.name }}-{{ substr 0 8 $.Values.global.env.INSTANCE_ID | lower }}
    type: DirectoryOrCreate
---
{{- end }}
{{- end }}

# `C:\Users\admin\data`
# `/c/Users/admin/data`
# `D:\projects\k8s\volume`
# `/d/projects/k8s/volume