apiVersion: v1
kind: Secret
metadata:
  name: wildcard-tls-secret
  namespace: {{ $.Values.global.appName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Values.global.tls.crt }}
  tls.key: {{ $.Values.global.tls.key }}
