apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.global.appName }}-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ $.Values.global.userHome }}/data/{{ $.Values.global.appName }}
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ $.Values.global.appName }}
    name: {{ $.Values.global.appName }}-pvc
---

# `C:\Users\admin\data`
# `/c/Users/admin/data`
# `D:\projects\k8s\volume`
# `/d/projects/k8s/volume