apiVersion: v1
kind: Secret
metadata:
  name: wildcard-tls-secret
  namespace: {{ $.Values.global.appName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ (lookup "v1" "Secret" "default" "wildcard-tls-secret") | default dict | dig "data" "tls.crt" "" | quote }}
  tls.key: {{ (lookup "v1" "Secret" "default" "wildcard-tls-secret") | default dict | dig "data" "tls.key" "" | quote }}
