apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.global.appName }}-server-postgres-pvc
  namespace: {{ $.Values.global.appName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeName: {{ $.Values.global.appName }}-server-postgres-pv
---
