global:
  imageRegistry: "docker.io/nocodebi"
  image:
    tag: "latest"
  ingress:
    className: "traefik"
    domain: nocodebi.io
  appName: app
  userHome: ""
  ingressURL: ""
  env:
    DATA_DIR: "/app/data/"
    CENTRAL_SERVER_URL: "https://central.nocodebi.io/"
    PRODUCT_CONSOLE_SERVER_URL: "https://product.nocodebi.io/"
    APP_SERVER_URL: ""
    STAGE_ID: ""
    APP_ID: ""
    VERSION_ID: ""
    USER_ID: ""
    PREMISES_SHA: ""
    CORE_JAR_URL: ""
    M2_ZIP_URL: ""
    APP_DATA_PATH: "/app/data/"
    INSTANCE_ID: ""
    DATABASE_ID: ""

services:

- name: appserver-hosted-database
  image: appserver-hosted-db
  port: 10004
  path: /hostedDB
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  enableVolume: true
  volume:
    size: 10Gi